"""Type stubs for the private native extension.

End users should not import from this module directly — use the public
``viva_genicam`` package instead.
"""

from typing import Any, Optional

class GigeDeviceInfo:
    ip: str
    mac: str
    manufacturer: Optional[str]
    model: Optional[str]

class U3vDeviceInfo:
    bus: int
    address: int
    vendor_id: int
    product_id: int
    serial: Optional[str]
    manufacturer: Optional[str]
    model: Optional[str]

class _Frame:
    width: int
    height: int
    pixel_format: str
    pixel_format_code: int
    ts_dev: Optional[int]
    ts_host: Optional[float]
    def payload(self) -> bytes: ...
    def to_numpy(self) -> Any: ...
    def to_rgb8(self) -> Any: ...

class _FrameStream:
    def next_frame(self, timeout_ms: Optional[int] = None) -> Optional[_Frame]: ...
    def close(self) -> None: ...
    def __iter__(self) -> "_FrameStream": ...
    def __next__(self) -> _Frame: ...

class _Camera:
    transport: str
    xml: str
    def get(self, name: str) -> str: ...
    def set(self, name: str, value: str) -> None: ...
    def set_exposure_time_us(self, value: float) -> None: ...
    def set_gain_db(self, value: float) -> None: ...
    def enum_entries(self, name: str) -> list[str]: ...
    def nodes(self) -> list[str]: ...
    def node_info(self, name: str) -> Optional[dict]: ...
    def all_node_info(self) -> list[dict]: ...
    def categories(self) -> dict[str, list[str]]: ...
    def acquisition_start(self) -> None: ...
    def acquisition_stop(self) -> None: ...
    def open_stream(
        self,
        iface: Optional[str],
        auto_packet_size: Optional[bool],
        multicast: Optional[str],
        destination_port: Optional[int],
    ) -> _FrameStream: ...

def discover_gige(
    timeout_ms: int = 500,
    iface: Optional[str] = None,
    all: bool = False,
) -> list[GigeDeviceInfo]: ...
def discover_u3v() -> list[U3vDeviceInfo]: ...
def connect_gige(
    device_info: GigeDeviceInfo, iface: Optional[str] = None
) -> _Camera: ...
def connect_u3v(device_info: U3vDeviceInfo) -> _Camera: ...

class GenicamError(Exception): ...
class GenApiError(GenicamError): ...
class TransportError(GenicamError): ...
class ParseError(GenicamError): ...
class MissingChunkFeatureError(GenicamError): ...
class UnsupportedPixelFormatError(GenicamError): ...
